### ISSUE TITLE
Dockerfile for the image (https://hub.docker.com/u/suwangbio)

### ISSUE THREAD

**Issue by MahShaaban** [suwangbio/BETA#1]
Hi,

I wonder if you could share the **Dockerfile** of this [image](https://hub.docker.com/u/suwangbio). It would be useful to be able to install BETA inside other images.

**Comment by DeemaAli1** [comment]
Hi, 
I got this error message, any idea?

Traceback (most recent call last):
  File "/home/genomicsmsc/Pictures/BETA_1.0.7/./bin/BETA", line 193, in <module>
    main()
  File "/home/genomicsmsc/Pictures/BETA_1.0.7/./bin/BETA", line 182, in main
    from BETA.runbeta import basicrun
ModuleNotFoundError: No module named 'BETA'
